### ISSUE TITLE
Problème  maj API

### ISSUE THREAD

**Issue by ebuard** [BaseAdresseNationale/ban#137]
Je signale ce matin un problème pour mettre à jour l'API.
Nous avons essayé de mettre à jour l'API avec pull. Le serveur se lançait avant le pull. Après le pull, en lançant ban server:run, nous avons ce type d'erreur: ImportError: No module named 'falcon_multipart'. En conséquence: il n'est pas possible d'obtenir les mises à jour de l'API.

**Comment by yohanboniface** [comment]
Il faut réinstaller les dépendances après chaque mise à jour, pour être sûr d'avoir les dernières versions:

`pip install -r requirements.txt` (voir le README)

**Comment by ebuard** [comment]
effectivement il y avait cette erreur.
Après mise à jour des dépendances, la commande ban server:run renvoie
Traceback (most recent call last):
  File "/home/idc/api-ban/banenv/bin/ban", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 644, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 657, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/idc/api-ban/banenv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'decorator==4.0.9' distribution was not found and is required by ban

**Comment by yohanboniface** [comment]
Lance, depuis la racine du code de la ban:

`python setup.py develop`

Pour adapter l'installation de la ban aux nouvelles dépendances.

**Comment by ebuard** [comment]
oui, ça marche!
