### ISSUE TITLE
Connexion lost

### ISSUE THREAD

**Issue by yohanboniface** [BaseAdresseNationale/ban#266]
From @odorie:

L’API répond pendant quelques heures puis elle renvoie un 500.
Si on redémarre uwsgi, elle répond de nouveau correctement pendant quelques heures puis ensuite de nouveau 500.
 
Nous avons installé l’API sur une machine et PostgreSQL sur une autre machine.
Nous avons créé un token de façon standard et modifié la date d’expiration du token à la main (on l’a mis jusqu’en 2018).
 
La fin du log uwsgi est la suivante :
 
```
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/ban/venv/lib/python3.4/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/ban/venv/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/ban/venv/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 555, in decorated
    valid, req = self.verify_request(scopes)
  File "/srv/ban/venv/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 483, in verify_request
    uri, http_method, body, headers, scopes
 File "/srv/ban/venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/srv/ban/venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 75, in verify_request
    return token_type_handler.validate_request(request), request
  File "/srv/ban/venv/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/tokens.py", line 294, in validate_request
    token, request.scopes, request)
  File "/srv/ban/venv/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 781, in validate_bearer_token
    tok = self._tokengetter(access_token=token)
  File "/srv/ban/src/ban/http/auth.py", line 42, in tokengetter
    token = models.Token.first(models.Token.access_token == access_token)
  File "/srv/ban/src/ban/db/model.py", line 77, in first
    return qs.limit(1).first()
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 3114, in first
    return self.peek(n=n)
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 3104, in peek
    res = self.execute()
  File "/srv/ban/src/ban/db/model.py", line 18, in execute
    wrapper = super().execute()
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 3149, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 2833, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/srv/ban/venv/lib/python3.4/site-packages/playhouse/postgres_ext.py", line 381, in execute_sql
    self.commit()
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 3514, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/srv/ban/venv/lib/python3.4/site-packages/peewee.py", line 134, in reraise
    raise value.with_traceback(tb)
  File "/srv/ban/venv/lib/python3.4/site-packages/playhouse/postgres_ext.py", line 372, in execute_sql
    cursor = self.get_cursor()
  File "/srv/ban/venv/lib/python3.4/site-packages/playhouse/postgres_ext.py", line 359, in get_cursor
    return self.get_conn().cursor()
peewee.InterfaceError: connection already closed
[pid: 34653|app: 0|req: 14/119] 10.10.0.2 () {50 vars in 750 bytes} [Fri Dec  9 08:53:05 2016] GET /group => generated 291 bytes in 6 msecs (HTTP/1.1 500) 4 headers in 154 bytes (1 switches on core 0)
 ```
 
Dans le log PostgreSQL, on a :
 
```
2016-12-08 12:22:47 CET [63978-1] ban@ban LOG:  n'a pas pu recevoir les données du client : Connexion terminée par expiration du délai d'attente
2016-12-08 21:54:23 CET [1033-1] ban@ban LOG:  n'a pas pu recevoir les données du client : Connexion terminée par expiration du délai d'attente
2016-12-08 21:57:31 CET [1017-1] ban@ban LOG:  n'a pas pu recevoir les données du client : Connexion terminée par expiration du délai d'attente
 ```
 
 We want to reconnect before any request, if needed.

**Comment by odorie** [comment]
Cette correction a corrigé notre souci d'instabilité.
L'API est en place chez nous depuis 2 jours et répond correctement.
Merci pour cette correction.
